jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    # FORZAMOS macOS para C-CPP y SWIFT
    runs-on: ${{ (matrix.language == 'c-cpp' || matrix.language == 'swift') && 'macos-latest' || 'ubuntu-latest' }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: c-cpp
          build-mode: manual
        # ... resto de lenguajes